name: Jamovi Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        r-version: ['3.6.3']  # Alterado para R 3.6.3

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}  # Configura a versão R 3.6.3

      - name: Install Jamovi dependencies for R 3.6.3
        run: |
          install.packages("remotes")
          remotes::install_version("jmvcore", version = "1.0.0", repos = "http://cran.us.r-project.org")  # Instala uma versão compatível com R 3.6.3
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Query jmvcore dependencies
        run: |
          jmvcore::check_jamovi_dependencies()
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-build-vignettes"), error_on = "warning") 
        shell: Rscript {0}
